### ISSUE TITLE
请问支持挂载私人仓库吗？

### ISSUE THREAD

**Issue by dishao123** [jianjianai/FList#8]
作者你好，请问一下是否支持挂载非公开仓库呢

**Comment by jianjianai** [comment]
目前是不可以的

**Comment by dishao123** [comment]
> 目前是不可以的

以后会支持吗？

**Comment by jianjianai** [comment]
> > 目前是不可以的
> 
> 以后会支持吗？

以后可能支持也可能不支持，这样干有点问题

**Comment by dishao123** [comment]
> > > 目前是不可以的
> > 
> > 
> > 以后会支持吗？
> 
> 以后可能支持也可能不支持，这样干有点问题

好吧
